android.permission.CHANGE_WIMAX_STATE", "android.permission.CLEAR_APP_CACHE",
"android.permission.DISABLE_KEYGUARD", "android.permission.EXPAND_STATUS_BAR",
"android.permission.FLASHLIGHT", "android.permission.GET_PACKAGE_SIZE", "android.permission.INTERNET",
"android.permission.KILL_BACKGROUND_PROCESSES", "android.permission.MODIFY_AUDIO_SETTINGS",
"android.permission.NFC", "android.permission.PERSISTENT_ACTIVITY",
"android.permission.READ_SYNC_SETTINGS", "android.permission.READ_USER_DICTIONARY",
"android.permission.RECEIVE_BOOT_COMPLETED", "android.permission.REORDER_TASKS",
"android.permission.SERIAL_PORT", "android.permission.SET_ALWAYS_FINISH",
"android.permission.SET_ANIMATION_SCALE", "android.permission.SET_DEBUG_APP",
"android.permission.SET_PREFERRED_APPLICATIONS", "android.permission.SET_PROCESS_LIMIT",
"android.permission.SET_TIME_ZONE", "android.permission.SET_WALLPAPER",
"android.permission.SIGNAL_PERSISTENT_PROCESSES", "android.permission.SYSTEM_ALERT_WINDOW",
"android.permission.USE_CREDENTIALS", "android.permission.USE_SIP", "android.permission.VIBRATE",
"android.permission.WAKE_LOCK", "android.permission.WRITE_SETTINGS",
"android.permission.WRITE_SYNC_SETTINGS", "android.permission.WRITE_USER_DICTIONARY",
"com.android.alarm.permission.SET_ALARM", "com.android.browser.permission.WRITE_HISTORY_BOOKMARKS",
"com.android.launcher.permission.INSTALL_SHORTCUT",
"com.android.launcher.permission.UNINSTALL_SHORTCUT", "com.android.vending.CHECK_LICENSE",
"com.google.android.providers.gsf.permissi
